### PR TITLE
Get this Atom Package Working Fully

### PR DESCRIPTION
**Pull request by mallardduck**
This PR will:

- Fix parameter causing incompatibility with PHPStan
- Update the linter to support the V2 API for Linter and Messages
- Get the package fully working again

### CODE REVIEW

**Comment by jeremyFreeAgent** [comment]
What about merging that one?

**Comment by mallardduck** [comment]
Thanks for the bump, would be cool to see this merged. It's a neat tool but not much use currently without this patch. paging @BradCrumb

**Comment by sbrl** [comment]
What's the status of this? Now that Serenata has removed linting, I'd love to install this package.

If there's no activity from the original developer, could someone fork it?

**Comment by jeremyFreeAgent** [comment]
> If there's no activity from the original developer, could someone fork it?

There is no licence on that project.

> What's the status of this? Now that Serenata has removed linting, I'd love to install this package.

You can update directly your local package with the fix of that PR. Works well.

**Comment by sbrl** [comment]
@jeremyFreeAgent Ahh, I see. I didn't check the licence - that's a shame :confused: 

How do I do that? I didn't think you could modify the packages you've installed without them being overwritten.

**Comment by mallardduck** [comment]
Actually @jeremyFreeAgent is wrong...

Just because there isn't a LICENSE.md file in project doesn't mean there is no license. You have to look thru the project since licensing isn't always as explicitly defined as that. In this case the package is MIT which means do w/e you want pretty much.

You can see this here:
https://github.com/BradCrumb/atom-linter-phpstan/blob/da48438851c61b257c182dce8591eb1d8bd0c25a/package.json#L16

**Comment by jeremyFreeAgent** [comment]
@sbrl 
`Atom` -> `Preferences` -> `Packages` -> search for atom-linter-phpstan in your installed packages -> `Settings` -> `View Code` -> change, save, and restart Atom

**Comment by jeremyFreeAgent** [comment]
@mallardduck by bad, thanks!

**Comment by mallardduck** [comment]
As I had forked the package to create the patch I just decided to go for it.
A new incarnation of this can be found here: https://atom.io/packages/linter-phpstan
The new repo is at: https://github.com/mallardduck/linter-phpstan

**Comment by mallardduck** [comment]
With some help from an issue submitted by @Gert-dev - my fork now has a working release.
So far it includes my patch submitted here, but if anyone else finds issues feel free to submit issues and/or PRs on my repo.

**Comment by mallardduck** [comment]
Hey @BradCrumb,

Can you please merge this PR and then get a new tag published to APM? Once that's done I can uninstall my fork and handle that how ever makes sense.

**Comment by mallardduck** [comment]
PS this should fix all open issues.

#3 #6 and #7

**Comment by BradCrumb** [comment]
@mallardduck Great job. Just published the updated version.

**Comment by sbrl** [comment]
Hey, @BradCrumb / @mallardduck! Should I report bugs here or to the fork?

I found another one:

```
[Linter] Error running PHPStan Error: PHPStan crashed in the previous run probably because of excessive memory consumption.
It consumed around 10 MB of memory.


To avoid this issue, allow to use more memory with the --memory-limit option.
    at ChildProcess.<anonymous> (/home/sbrl/.atom/pac…xec/lib/index.js:56)
    at emitTwo (events.js:126)
    at ChildProcess.emit (events.js:214)
    at maybeClose (internal/child_process.js:925)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209)
```

For reference, the default limit is 100M, and tried it with 1024M and it still didn't work (it didn't use anywhere _near_ that amount of memory).

It works absolutely fine on the command line:

```
$ ~/.config/composer/vendor/phpstan/phpstan/bin/phpstan analyse core/02-environment.php  --level 0
Note: Using configuration file some/path/to/peppermint/phpstan.neon.
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

                                                                                
 [OK] No errors                                                       
```

**Comment by BradCrumb** [comment]
@sbrl Hi there, can you please create a new Issue for this. It is easy to miss when you report this in a closed issue ;). 

Thank you.

**Comment by sbrl** [comment]
Sure, @BradCrumb!

**Edit:** The new issue is [here](https://github.com/BradCrumb/atom-linter-phpstan/issues/9)

**Pull request merged**
